---
- name: Deploy Java application
  hosts: all
  gather_facts: no
  roles:
    - cdk_role
  tasks:
    - name: Deploy Java app in dev
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_java_app/dev"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_dev"

    - name: Deploy Java app in qa
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_java_app/qa"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_qa"

    - name: Deploy Java app in preprod
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_java_app/preprod"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_preprod"

    - name: Deploy Java app in prod
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_java_app/prod"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_prod"

    - name: Deploy Java app in training
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_java_app/training"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_training"
