---
- name: Deploy Node.js application
  hosts: all
  gather_facts: no
  roles:
    - cdk_role
  tasks:
    - name: Deploy Node.js app in dev
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_nodejs_app/dev"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_dev"

    - name: Deploy Node.js app in qa
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_nodejs_app/qa"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_qa"

    - name: Deploy Node.js app in preprod
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_nodejs_app/preprod"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_preprod"

    - name: Deploy Node.js app in prod
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_nodejs_app/prod"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_prod"

    - name: Deploy Node.js app in training
      command: cdk deploy
      args:
        chdir: "../../apps/search_jobs_nodejs_app/training"
      when: ansible_env.AWS_PROFILE == "llm_search_jobs_app_training"
